import React, { useState, useEffect } from 'react';

// --- LIVE DEMO COMPONENTS ---

const GenAiDemo = () => {
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<{role: string, text: string}[]>([{ role: 'ai', text: 'Hi, how can I help you draft content or answer questions today?' }]);
  const [isTyping, setIsTyping] = useState(false);

  const handleSend = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;
    setMessages(prev => [...prev, { role: 'user', text: input }]);
    setInput('');
    setIsTyping(true);
    setTimeout(() => {
      setMessages(prev => [...prev, { role: 'ai', text: 'Based on your enterprise data, here is a sophisticated response generated by our fine-tuned LLM. Notice the context retention and domain-specific vocabulary.' }]);
      setIsTyping(false);
    }, 1500);
  };

  return (
    <div style={{ background: '#FFFFFF', borderRadius: 24, padding: 24, boxShadow: '0 20px 40px rgba(0,0,0,0.05)', border: '1px solid rgba(0,0,0,0.05)', height: 400, display: 'flex', flexDirection: 'column' }}>
      <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 16 }}>
        {messages.map((m, i) => (
          <div key={i} style={{ alignSelf: m.role === 'ai' ? 'flex-start' : 'flex-end', background: m.role === 'ai' ? '#F8FAFC' : '#6366F1', color: m.role === 'ai' ? '#0F172A' : '#FFFFFF', padding: '12px 16px', borderRadius: m.role === 'ai' ? '16px 16px 16px 0' : '16px 16px 0 16px', maxWidth: '85%', fontSize: 14 }}>
            {m.text}
          </div>
        ))}
        {isTyping && (
          <div style={{ alignSelf: 'flex-start', background: '#F8FAFC', padding: '12px 16px', borderRadius: '16px 16px 16px 0', fontSize: 14, color: '#94A3B8', display: 'flex', gap: 4 }}>
            <span style={{ animation: 'bounce 1.4s infinite ease-in-out both' }}>.</span>
            <span style={{ animation: 'bounce 1.4s infinite ease-in-out both', animationDelay: '0.2s' }}>.</span>
            <span style={{ animation: 'bounce 1.4s infinite ease-in-out both', animationDelay: '0.4s' }}>.</span>
          </div>
        )}
      </div>
      <form onSubmit={handleSend} style={{ display: 'flex', gap: 8 }}>
        <input value={input} onChange={e => setInput(e.target.value)} placeholder="Type a prompt..." style={{ flex: 1, background: '#F8FAFC', border: '1px solid rgba(0,0,0,0.1)', borderRadius: 100, padding: '12px 20px', outline: 'none' }} />
        <button type="submit" style={{ background: '#0F172A', color: 'white', border: 'none', borderRadius: 100, padding: '0 24px', fontWeight: 600, cursor: 'pointer' }}>Send</button>
      </form>
    </div>
  );
};

const VisionDemo = () => {
  const [analyzing, setAnalyzing] = useState(false);
  const [boxes, setBoxes] = useState(false);

  const analyze = () => {
    setBoxes(false);
    setAnalyzing(true);
    setTimeout(() => { setAnalyzing(false); setBoxes(true); }, 2000);
  };

  return (
    <div style={{ background: '#FFFFFF', borderRadius: 24, padding: 24, boxShadow: '0 20px 40px rgba(0,0,0,0.05)', border: '1px solid rgba(0,0,0,0.05)', height: 400, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ width: '100%', height: 260, background: '#F8FAFC', borderRadius: 16, position: 'relative', overflow: 'hidden', backgroundImage: 'url(https://images.unsplash.com/photo-1580261450046-d0a30080dc9b?w=600&q=80)', backgroundSize: 'cover', backgroundPosition: 'center' }}>
        {analyzing && (
          <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 4, background: '#0EA5E9', boxShadow: '0 0 20px #0EA5E9', animation: 'scan 2s linear infinite' }} />
        )}
        {boxes && (
          <>
            <div style={{ position: 'absolute', top: '20%', left: '30%', width: '40%', height: '50%', border: '2px solid #10B981', borderRadius: 4, background: 'rgba(16,185,129,0.2)' }}>
              <span style={{ background: '#10B981', color: 'white', fontSize: 10, padding: '2px 6px', position: 'absolute', top: -18, left: -2, fontWeight: 'bold' }}>Person 98%</span>
            </div>
            <div style={{ position: 'absolute', top: '60%', left: '10%', width: '20%', height: '30%', border: '2px solid #0EA5E9', borderRadius: 4, background: 'rgba(14,165,233,0.2)' }}>
              <span style={{ background: '#0EA5E9', color: 'white', fontSize: 10, padding: '2px 6px', position: 'absolute', top: -18, left: -2, fontWeight: 'bold' }}>Bag 92%</span>
            </div>
          </>
        )}
      </div>
      <button onClick={analyze} disabled={analyzing} style={{ marginTop: 24, background: '#0EA5E9', color: 'white', border: 'none', borderRadius: 100, padding: '12px 32px', fontWeight: 600, cursor: analyzing ? 'not-allowed' : 'pointer' }}>
        {analyzing ? 'Running Inference...' : 'Analyze Image'}
      </button>
      <style>{`@keyframes scan { 0% { transform: translateY(0); } 50% { transform: translateY(260px); } 100% { transform: translateY(0); } }`}</style>
    </div>
  );
};

const PredictiveDemo = () => {
  return (
    <div style={{ background: '#FFFFFF', borderRadius: 24, padding: 24, boxShadow: '0 20px 40px rgba(0,0,0,0.05)', border: '1px solid rgba(0,0,0,0.05)', height: 400, display: 'flex', flexDirection: 'column' }}>
      <div style={{ fontSize: 14, fontWeight: 700, color: '#64748B', marginBottom: 16 }}>REVENUE FORECAST MODEL</div>
      <div style={{ flex: 1, display: 'flex', alignItems: 'flex-end', gap: 12, paddingBottom: 20, borderBottom: '1px dashed #E2E8F0', position: 'relative' }}>
        {[40, 50, 45, 60, 75, 85, 80].map((h, i) => (
          <div key={i} style={{ flex: 1, height: `${h}%`, background: i > 4 ? '#E2E8F0' : '#10B981', borderRadius: 4, position: 'relative', animation: `growUp 1s ease-out forwards ${i * 0.1}s`, transformOrigin: 'bottom', transform: 'scaleY(0)' }}>
            {i === 5 && <div style={{ position: 'absolute', top: -30, left: '50%', transform: 'translateX(-50%)', background: '#0F172A', color: 'white', fontSize: 10, padding: '4px 8px', borderRadius: 4, whiteSpace: 'nowrap' }}>Prediction</div>}
          </div>
        ))}
      </div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 16, color: '#94A3B8', fontSize: 12 }}>
        <span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span style={{color:'#10B981', fontWeight: 700}}>Jun</span><span style={{color:'#10B981', fontWeight: 700}}>Jul</span>
      </div>
      <style>{`@keyframes growUp { from { transform: scaleY(0); } to { transform: scaleY(1); } }`}</style>
    </div>
  );
};

const AutomationDemo = () => {
  const [step, setStep] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => setStep(s => (s + 1) % 4), 2000);
    return () => clearInterval(timer);
  }, []);

  const nodes = [
    { label: 'Incoming Email', x: 20, y: 50, color: '#94A3B8' },
    { label: 'AI Classification', x: 50, y: 50, color: '#F59E0B' },
    { label: 'Update CRM', x: 80, y: 20, color: '#10B981' },
    { label: 'Slack Alert', x: 80, y: 80, color: '#0EA5E9' },
  ];

  return (
    <div style={{ background: '#FFFFFF', borderRadius: 24, padding: 24, boxShadow: '0 20px 40px rgba(0,0,0,0.05)', border: '1px solid rgba(0,0,0,0.05)', height: 400, position: 'relative' }}>
      <div style={{ fontSize: 14, fontWeight: 700, color: '#64748B', marginBottom: 24 }}>WORKFLOW AGENT</div>
      {nodes.map((n, i) => (
        <div key={i} style={{ position: 'absolute', top: `${n.y}%`, left: `${n.x}%`, transform: 'translate(-50%, -50%)', background: step >= i ? n.color : '#F1F5F9', color: step >= i ? 'white' : '#94A3B8', padding: '10px 16px', borderRadius: 12, fontSize: 12, fontWeight: 600, transition: 'all 0.5s', boxShadow: step === i ? `0 0 20px ${n.color}` : 'none', zIndex: 2 }}>
          {n.label}
        </div>
      ))}
      <svg style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', zIndex: 1 }}>
        <path d="M 120 180 L 250 180" stroke="#E2E8F0" strokeWidth="2" strokeDasharray="5,5" />
        <path d="M 330 170 L 410 100" stroke="#E2E8F0" strokeWidth="2" strokeDasharray="5,5" />
        <path d="M 330 190 L 410 260" stroke="#E2E8F0" strokeWidth="2" strokeDasharray="5,5" />
      </svg>
    </div>
  );
};

const NlpDemo = () => {
  const [text, setText] = useState('We are extremely disappointed with the new update. The interface is confusing and our team is losing productivity. However, customer support was very helpful.');
  const [analyzing, setAnalyzing] = useState(false);
  const [result, setResult] = useState<any>(null);

  const analyze = () => {
    setAnalyzing(true);
    setResult(null);
    setTimeout(() => {
      setAnalyzing(false);
      setResult({
        sentiment: 'Mixed / Negative',
        entities: ['Update', 'Interface', 'Customer Support'],
        intent: 'Complaint / Feedback'
      });
    }, 1500);
  };

  return (
    <div style={{ background: '#FFFFFF', borderRadius: 24, padding: 24, boxShadow: '0 20px 40px rgba(0,0,0,0.05)', border: '1px solid rgba(0,0,0,0.05)', height: 400, display: 'flex', flexDirection: 'column' }}>
      <textarea value={text} onChange={e => setText(e.target.value)} style={{ width: '100%', height: 120, background: '#F8FAFC', border: '1px solid rgba(0,0,0,0.1)', borderRadius: 16, padding: 16, outline: 'none', resize: 'none', marginBottom: 16 }} />
      <button onClick={analyze} disabled={analyzing} style={{ background: '#EC4899', color: 'white', border: 'none', borderRadius: 100, padding: '12px', fontWeight: 600, cursor: analyzing ? 'not-allowed' : 'pointer' }}>{analyzing ? 'Extracting Meaning...' : 'Analyze Text'}</button>
      
      {result && (
        <div style={{ marginTop: 24, animation: 'fadeInUp 0.5s ease-out' }}>
          <div style={{ display: 'flex', gap: 12, marginBottom: 12 }}>
            <span style={{ background: 'rgba(236,72,153,0.1)', color: '#EC4899', padding: '6px 12px', borderRadius: 8, fontSize: 12, fontWeight: 700 }}>Sentiment: {result.sentiment}</span>
            <span style={{ background: 'rgba(99,102,241,0.1)', color: '#6366F1', padding: '6px 12px', borderRadius: 8, fontSize: 12, fontWeight: 700 }}>Intent: {result.intent}</span>
          </div>
          <div style={{ fontSize: 12, color: '#64748B', fontWeight: 600 }}>ENTITIES FOUND:</div>
          <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
            {result.entities.map((e: string, i: number) => <span key={i} style={{ background: '#F1F5F9', padding: '4px 8px', borderRadius: 4, fontSize: 12, color: '#475569' }}>{e}</span>)}
          </div>
        </div>
      )}
    </div>
  );
};

const CustomModelDemo = () => {
  return (
    <div style={{ background: '#0F172A', borderRadius: 24, padding: 24, boxShadow: '0 20px 40px rgba(0,0,0,0.1)', height: 400, display: 'flex', flexDirection: 'column', color: '#F8FAFC' }}>
      <div style={{ fontSize: 14, fontWeight: 700, color: '#94A3B8', marginBottom: 16, display: 'flex', justifyContent: 'space-between' }}>
        <span>MODEL TRAINING LOOP</span>
        <span style={{ color: '#8B5CF6' }}>EPOCH 42/100</span>
      </div>
      <div style={{ flex: 1, fontFamily: 'monospace', fontSize: 13, background: '#020617', padding: 16, borderRadius: 12, overflow: 'hidden', position: 'relative' }}>
        <div style={{ animation: 'scrollUp 5s linear infinite', position: 'absolute', bottom: -100 }}>
          <div style={{ color: '#10B981' }}>[OK] Batch 1400: Loss = 0.0421</div>
          <div style={{ color: '#10B981' }}>[OK] Batch 1401: Loss = 0.0418</div>
          <div style={{ color: '#10B981' }}>[OK] Batch 1402: Loss = 0.0415</div>
          <div style={{ color: '#0EA5E9' }}>-- Adjusting learning rate --</div>
          <div style={{ color: '#10B981' }}>[OK] Batch 1403: Loss = 0.0390</div>
          <div style={{ color: '#10B981' }}>[OK] Batch 1404: Loss = 0.0385</div>
          <div style={{ color: '#E2E8F0' }}>Evaluating validation set...</div>
          <div style={{ color: '#8B5CF6' }}>Val Accuracy: 96.4%</div>
        </div>
      </div>
      <style>{`@keyframes scrollUp { from { transform: translateY(0); } to { transform: translateY(-100px); } }`}</style>
    </div>
  );
}


// --- DATA EXPORT ---

export const aiPageData: Record<string, any> = {
  'generative-ai': {
    slug: 'generative-ai',
    metaTitle: 'Generative AI Integration | DevBotics',
    heroH1: ['Generative AI', 'Integration'],
    heroSub: 'Build autonomous agents and custom LLMs tailored to your enterprise data. We deploy private, secure GPT and Claude models that understand your business.',
    heroAccentWord: 'Intelligent.',
    color: '#6366F1',
    DemoComponent: GenAiDemo,
    features: [
      { t: 'Custom Chatbots', d: 'Context-aware agents integrated into your product.' },
      { t: 'Retrieval Augmented Generation', d: 'Connect LLMs to your private databases securely.' },
      { t: 'Content Automation', d: 'Auto-generate reports, marketing copy, and emails.' }
    ],
    tech: ['OpenAI', 'Anthropic', 'LangChain', 'Pinecone', 'LlamaIndex'],
    related: ['natural-language-processing', 'intelligent-automation']
  },
  'computer-vision': {
    slug: 'computer-vision',
    metaTitle: 'Computer Vision Systems | DevBotics',
    heroH1: ['Computer', 'Vision'],
    heroSub: 'Real-time image recognition, object detection, and visual QA systems. Turn raw video feeds into structured, actionable business intelligence.',
    heroAccentWord: 'Visualized.',
    color: '#0EA5E9',
    DemoComponent: VisionDemo,
    features: [
      { t: 'Object Detection', d: 'Identify and track multiple objects in real-time.' },
      { t: 'Facial Recognition', d: 'Secure biometric authentication and analysis.' },
      { t: 'Quality Control', d: 'Automated visual inspection for manufacturing.' }
    ],
    tech: ['OpenCV', 'YOLO', 'TensorFlow', 'PyTorch', 'CUDA'],
    related: ['predictive-analytics', 'custom-ai-architectures']
  },
  'predictive-analytics': {
    slug: 'predictive-analytics',
    metaTitle: 'Predictive Analytics | DevBotics',
    heroH1: ['Predictive', 'Analytics'],
    heroSub: 'Advanced Machine Learning models that forecast sales, detect anomalies, and predict customer churn before it happens.',
    heroAccentWord: 'Foresight.',
    color: '#10B981',
    DemoComponent: PredictiveDemo,
    features: [
      { t: 'Demand Forecasting', d: 'Predict inventory needs with 95%+ accuracy.' },
      { t: 'Anomaly Detection', d: 'Identify fraud or system failures instantly.' },
      { t: 'Customer Churn', d: 'ML models that flag at-risk users early.' }
    ],
    tech: ['Scikit-Learn', 'XGBoost', 'Prophet', 'Pandas', 'AWS SageMaker'],
    related: ['generative-ai', 'computer-vision']
  },
  'intelligent-automation': {
    slug: 'intelligent-automation',
    metaTitle: 'Intelligent Automation | DevBotics',
    heroH1: ['Intelligent', 'Automation'],
    heroSub: 'Replace repetitive operational tasks with self-learning AI workflows. Reduce manual overhead by up to 80% with smart agents.',
    heroAccentWord: 'Seamless.',
    color: '#F59E0B',
    DemoComponent: AutomationDemo,
    features: [
      { t: 'Document Parsing', d: 'Extract structured data from PDFs and images.' },
      { t: 'Workflow Agents', d: 'AI that operates your SaaS tools autonomously.' },
      { t: 'Support Triage', d: 'Auto-route tickets based on intent and sentiment.' }
    ],
    tech: ['Make', 'Zapier', 'Python', 'UiPath', 'OpenAI APIs'],
    related: ['natural-language-processing', 'generative-ai']
  },
  'natural-language-processing': {
    slug: 'natural-language-processing',
    metaTitle: 'Natural Language Processing | DevBotics',
    heroH1: ['Natural Language', 'Processing'],
    heroSub: 'Deep document understanding, sentiment analysis, and intelligent text extraction. Turn unstructured text into a structured database.',
    heroAccentWord: 'Understood.',
    color: '#EC4899',
    DemoComponent: NlpDemo,
    features: [
      { t: 'Sentiment Analysis', d: 'Measure user emotion across millions of reviews.' },
      { t: 'Entity Extraction', d: 'Pull names, dates, and amounts from raw text.' },
      { t: 'Semantic Search', d: 'Search engines that understand context, not just keywords.' }
    ],
    tech: ['Hugging Face', 'Spacy', 'BERT', 'Transformers', 'Elasticsearch'],
    related: ['generative-ai', 'intelligent-automation']
  },
  'custom-ai-architectures': {
    slug: 'custom-ai-architectures',
    metaTitle: 'Custom AI Models | DevBotics',
    heroH1: ['Custom AI', 'Architectures'],
    heroSub: 'Proprietary Machine Learning models built from scratch. When off-the-shelf APIs aren\'t enough, we engineer bespoke AI for your exact needs.',
    heroAccentWord: 'Bespoke.',
    color: '#8B5CF6',
    DemoComponent: CustomModelDemo,
    features: [
      { t: 'Model Training', d: 'From data collection to hyperparameter tuning.' },
      { t: 'Edge AI', d: 'Deploy lightweight models directly to mobile or IoT.' },
      { t: 'Fine-Tuning', d: 'Adapt open-source models (Llama 3, Mistral) to your data.' }
    ],
    tech: ['PyTorch', 'TensorFlow', 'CUDA', 'Ray', 'Kubernetes'],
    related: ['computer-vision', 'predictive-analytics']
  }
};
