export interface AppPageData {
  slug: string;
  metaTitle: string;
  metaDesc: string;
  heroEyebrow: string;
  heroH1: string[];
  heroAccentWord: string;
  heroSub: string;
  heroImage: string;
  overviewFeatures: { title: string; desc: string }[];
  panels: string[];
  techStack: string[];
  pricingStarter: string;
  pricingPro: string;
  pricingEnterprise: string;
  relatedSlugs: string[];
  faq: { q: string; a: string }[];
}

export const appPageData: Record<string, AppPageData> = {
  'food-delivery': {
    slug: 'food-delivery',
    metaTitle: 'Food Delivery App Development Company | DevBotics',
    metaDesc: 'Build your own Swiggy or Zomato with DevBotics. Expert food delivery app development with real-time tracking, multi-restaurant support & payment integration.',
    heroEyebrow: '✦ APP DEVELOPMENT · FOOD DELIVERY',
    heroH1: ['Food Delivery App', 'Development'],
    heroAccentWord: 'Company.',
    heroSub: 'Build your own Swiggy or Zomato — feature-rich, scalable, and ready to launch in your city.',
    heroImage: '/images/generic-2.png',
    overviewFeatures: [
      { title: 'Real-Time Order Tracking', desc: 'Live GPS map tracking for customers from order to doorstep.' },
      { title: 'Multi-Restaurant Support', desc: 'Multiple vendors on one platform with individual dashboards.' },
      { title: 'Smart Search & Filters', desc: 'Cuisine, ratings, delivery time and dietary filters.' },
      { title: 'Promo & Coupon Engine', desc: 'Discount codes, first-order offers and referral rewards.' },
      { title: 'In-App Wallet & Payments', desc: 'Razorpay, UPI, cards, wallets and COD support.' },
      { title: 'Ratings & Reviews', desc: 'Verified customer feedback with photo upload.' },
    ],
    panels: ['Customer App', 'Restaurant Panel', 'Delivery Partner App', 'Admin Dashboard', 'Analytics Panel'],
    techStack: ['React Native', 'Node.js', 'MongoDB', 'Firebase', 'Google Maps API', 'Razorpay', 'AWS', 'Socket.io'],
    pricingStarter: '₹1,20,000',
    pricingPro: '₹2,80,000',
    pricingEnterprise: 'Custom',
    relatedSlugs: ['taxi-booking', 'on-demand-app', 'ecommerce-app'],
    faq: [
      { q: 'How long to build a food delivery app?', a: 'A complete solution with all 4 panels takes 8–14 weeks.' },
      { q: 'Can I launch in multiple cities?', a: 'Yes. Multi-city and multi-zone support is included in Professional and Enterprise plans.' },
      { q: 'Will it work like Swiggy/Zomato?', a: 'Yes. We build full clone-level functionality plus custom features unique to your brand.' },
      { q: 'Can restaurants manage their own menu?', a: 'Yes. Each restaurant gets a dedicated panel to manage menu, pricing, timing, and offers.' },
      { q: 'What payment methods are supported?', a: 'UPI, credit/debit cards, wallets, net banking, and Cash on Delivery.' },
      { q: 'Can I add my own delivery fleet?', a: 'Yes. The delivery partner app supports your own fleet or freelance drivers.' },
      { q: 'Is the admin panel included?', a: 'Yes, in Professional and Enterprise plans with full analytics and settings.' },
      { q: 'Do you provide server setup?', a: 'Yes. We set up AWS/Google Cloud with auto-scaling for peak order loads.' },
    ],
  },
  'taxi-booking': {
    slug: 'taxi-booking',
    metaTitle: 'Taxi Booking App Development Company | DevBotics',
    metaDesc: 'Launch your own Ola or Uber with DevBotics. Complete ride-hailing app with live tracking, dynamic pricing, driver & rider apps — fully white-labeled.',
    heroEyebrow: '✦ APP DEVELOPMENT · TAXI BOOKING',
    heroH1: ['Taxi Booking App', 'Development'],
    heroAccentWord: 'Company.',
    heroSub: 'Launch your own Ola or Uber — complete ride-hailing platform, fully white-labeled and ready to scale.',
    heroImage: '/images/generic-1.png',
    overviewFeatures: [
      { title: 'Live Driver Tracking', desc: 'Real-time GPS tracking of driver on interactive map.' },
      { title: 'Smart Fare Calculator', desc: 'Dynamic pricing based on distance, time and surge.' },
      { title: 'Ride Scheduling', desc: 'Book rides in advance for a specific date and time.' },
      { title: 'Multiple Ride Types', desc: 'Bike, auto, cab, SUV — all on one platform.' },
      { title: 'In-App Payments', desc: 'Wallet, UPI, card and cash support.' },
      { title: 'Driver Verification', desc: 'Document upload, KYC and approval workflow.' },
    ],
    panels: ['Rider App', 'Driver App', 'Admin Dashboard', 'Dispatcher Panel', 'Analytics'],
    techStack: ['Flutter', 'Node.js', 'MongoDB', 'Google Maps API', 'Firebase', 'Stripe', 'AWS', 'Socket.io'],
    pricingStarter: '₹1,50,000',
    pricingPro: '₹3,20,000',
    pricingEnterprise: 'Custom',
    relatedSlugs: ['food-delivery', 'on-demand-app', 'custom-mobile-app'],
    faq: [
      { q: 'How long does it take to build a taxi app?', a: 'A full rider + driver + admin solution takes 10–16 weeks.' },
      { q: 'Can I support multiple vehicle types?', a: 'Yes — bikes, autos, cabs and SUVs can all be configured.' },
      { q: 'Is surge pricing supported?', a: 'Yes. Dynamic fare calculation based on demand zones is included.' },
      { q: 'Can drivers set their own availability?', a: 'Yes. Drivers can go online/offline and choose ride preferences.' },
      { q: 'Do you include driver verification?', a: 'Yes — document upload, selfie KYC and admin approval workflow.' },
      { q: 'Is cash payment supported?', a: 'Yes. Cash, UPI, cards and in-app wallet are all supported.' },
      { q: 'Can I white-label this app?', a: 'Yes. The app is fully white-labeled with your brand and domain.' },
      { q: 'Do you handle Play Store submission?', a: 'Yes. We handle both Play Store and App Store submission for you.' },
    ],
  },
  'ecommerce-app': {
    slug: 'ecommerce-app',
    metaTitle: 'E-Commerce App Development Company | DevBotics',
    metaDesc: 'Build a high-converting shopping app with DevBotics. Feature-rich e-commerce mobile app with seamless checkout, product catalog, order tracking and payments.',
    heroEyebrow: '✦ APP DEVELOPMENT · E-COMMERCE',
    heroH1: ['E-commerce App', 'Development'],
    heroAccentWord: 'Company.',
    heroSub: 'Build a shopping app your customers can\'t stop using — fast, beautiful, and built to convert.',
    heroImage: '/images/generic-2.png',
    overviewFeatures: [
      { title: 'Product Catalog & Search', desc: 'Advanced filters, smart search and category browsing.' },
      { title: 'Secure Checkout', desc: 'One-tap checkout with saved addresses and payment methods.' },
      { title: 'Wishlist & Cart', desc: 'Smart cart with save-for-later and abandoned cart recovery.' },
      { title: 'Order Tracking', desc: 'Real-time delivery status with SMS and push notifications.' },
      { title: 'Multi-Payment Support', desc: 'UPI, cards, wallets, net banking, EMI options.' },
      { title: 'Review & Rating System', desc: 'Verified buyer reviews with photo and video support.' },
    ],
    panels: ['Customer App', 'Seller Panel', 'Admin Dashboard', 'Delivery Panel', 'Analytics'],
    techStack: ['React Native', 'Node.js', 'MongoDB', 'Stripe', 'Razorpay', 'AWS', 'Elasticsearch', 'Redis'],
    pricingStarter: '₹90,000',
    pricingPro: '₹2,20,000',
    pricingEnterprise: 'Custom',
    relatedSlugs: ['food-delivery', 'on-demand-app', 'custom-mobile-app'],
    faq: [
      { q: 'How long does an e-commerce app take to build?', a: 'A standard shopping app takes 6–12 weeks. Multi-vendor marketplaces take 12–20 weeks.' },
      { q: 'Can multiple sellers list products?', a: 'Yes. Multi-vendor marketplace support is available in Professional and Enterprise plans.' },
      { q: 'Which payment gateways do you support?', a: 'Razorpay, Stripe, PayU, PayPal, and all major Indian payment gateways.' },
      { q: 'Can I connect it to my existing website?', a: 'Yes. We can sync the app with your existing Shopify, WooCommerce, or custom backend.' },
      { q: 'Is an admin panel included?', a: 'Yes — product management, order tracking, analytics and user management.' },
      { q: 'Do you support product variants?', a: 'Yes — size, color, weight and any custom attribute variants.' },
      { q: 'Can I run promotional offers?', a: 'Yes — discount codes, flash sales, buy-one-get-one and loyalty points.' },
      { q: 'Is the app SEO friendly for app stores?', a: 'Yes. We handle full ASO (App Store Optimization) during submission.' },
    ],
  },
  'healthcare-app': {
    slug: 'healthcare-app',
    metaTitle: 'Healthcare App Development Company | DevBotics',
    metaDesc: 'HIPAA-compliant healthcare app development by DevBotics. Patient management, telemedicine, EMR and hospital management systems built for scale.',
    heroEyebrow: '✦ APP DEVELOPMENT · HEALTHCARE',
    heroH1: ['Healthcare App', 'Development'],
    heroAccentWord: 'Company.',
    heroSub: 'HIPAA-compliant patient apps, telemedicine platforms and hospital management systems built to scale.',
    heroImage: '/images/generic-1.png',
    overviewFeatures: [
      { title: 'Doctor Appointment Booking', desc: 'Calendar management with slot booking and reminders.' },
      { title: 'Telemedicine / Video Calls', desc: 'Encrypted video consultations between patient and doctor.' },
      { title: 'Electronic Health Records', desc: 'Secure patient history accessible only to authorized users.' },
      { title: 'Prescription Management', desc: 'Digital prescriptions, e-signature and medication reminders.' },
      { title: 'Lab Reports Integration', desc: 'Upload, share and view reports directly in the app.' },
      { title: 'Health Tracking', desc: 'Vitals, steps, sleep, medication and appointment reminders.' },
    ],
    panels: ['Patient App', 'Doctor Panel', 'Admin Dashboard', 'Pharmacy Module', 'Lab Module'],
    techStack: ['Flutter', 'Node.js', 'PostgreSQL', 'WebRTC', 'Firebase', 'AWS', 'HL7/FHIR'],
    pricingStarter: '₹1,40,000',
    pricingPro: '₹3,00,000',
    pricingEnterprise: 'Custom',
    relatedSlugs: ['edtech-app', 'custom-mobile-app', 'on-demand-app'],
    faq: [
      { q: 'Is the app HIPAA compliant?', a: 'Yes. We follow HIPAA guidelines for data encryption, access control and audit trails.' },
      { q: 'Can patients book appointments online?', a: 'Yes. Patients can view doctor availability, book slots and get reminders.' },
      { q: 'Is video consultation supported?', a: 'Yes. Encrypted WebRTC-based video calls are built into the patient and doctor apps.' },
      { q: 'Can doctors manage prescriptions digitally?', a: 'Yes. Digital prescriptions with e-signature and download options are included.' },
      { q: 'Is the app multi-specialty capable?', a: 'Yes. Multiple departments, specialties and doctors are supported.' },
      { q: 'Do you integrate lab and pharmacy modules?', a: 'Yes — lab report upload and pharmacy integration are available in Pro and Enterprise plans.' },
      { q: 'What security standards do you follow?', a: 'AES-256 encryption, role-based access, audit logs and secure AWS hosting.' },
      { q: 'How long does development take?', a: 'A core patient + doctor app takes 10–16 weeks. Full hospital ERP takes 4–6 months.' },
    ],
  },
  'edtech-app': {
    slug: 'edtech-app',
    metaTitle: 'EdTech App Development Company | DevBotics',
    metaDesc: 'Build powerful e-learning and EdTech apps with DevBotics. Live classes, LMS, student progress tracking and school management systems for India and beyond.',
    heroEyebrow: '✦ APP DEVELOPMENT · EDTECH',
    heroH1: ['EdTech App', 'Development'],
    heroAccentWord: 'Company.',
    heroSub: 'Online learning platforms, live class apps and school management systems built to scale.',
    heroImage: '/images/generic-2.png',
    overviewFeatures: [
      { title: 'Live Video Classes', desc: 'Real-time streaming with chat, reactions and polls.' },
      { title: 'Course & Content Management', desc: 'Video, PDF, quiz and interactive content organization.' },
      { title: 'Progress Tracking', desc: 'Student performance analytics and completion tracking.' },
      { title: 'Gamification', desc: 'Badges, leaderboards, streaks and reward points.' },
      { title: 'Doubt Solving', desc: 'In-app Q&A forum and one-on-one chat with teachers.' },
      { title: 'Certificate Generation', desc: 'Auto PDF certificate issuance on course completion.' },
    ],
    panels: ['Student App', 'Teacher Panel', 'Admin Dashboard', 'Parent Portal', 'Analytics'],
    techStack: ['React Native', 'Node.js', 'MongoDB', 'WebRTC', 'AWS S3', 'Razorpay', 'Firebase'],
    pricingStarter: '₹1,00,000',
    pricingPro: '₹2,50,000',
    pricingEnterprise: 'Custom',
    relatedSlugs: ['healthcare-app', 'custom-mobile-app', 'on-demand-app'],
    faq: [
      { q: 'Can I host pre-recorded and live classes?', a: 'Yes. Both live streaming and pre-recorded video courses are supported.' },
      { q: 'Is the platform multi-teacher capable?', a: 'Yes. Multiple teachers can manage their own courses and students.' },
      { q: 'Can parents track their child\'s progress?', a: 'Yes. A parent portal with attendance, grades and activity is available.' },
      { q: 'Do you support offline access?', a: 'Yes. Videos and PDFs can be downloaded for offline viewing.' },
      { q: 'Can students take tests and quizzes?', a: 'Yes. Timed quizzes, MCQ tests and instant result reports are included.' },
      { q: 'Is payment integration included?', a: 'Yes. Razorpay and Stripe for course purchases and subscriptions.' },
      { q: 'Can I issue certificates automatically?', a: 'Yes. PDF certificates are auto-generated upon course completion.' },
      { q: 'How long does it take to build?', a: 'A standard LMS takes 8–14 weeks. A full school ERP takes 4–6 months.' },
    ],
  },
  'on-demand-app': {
    slug: 'on-demand-app',
    metaTitle: 'On-Demand Service App Development Company | DevBotics',
    metaDesc: 'Build your on-demand service app for home cleaning, beauty, plumbing and more with DevBotics. Full platform with booking, tracking and payments.',
    heroEyebrow: '✦ APP DEVELOPMENT · ON-DEMAND',
    heroH1: ['On-Demand Service App', 'Development'],
    heroAccentWord: 'Company.',
    heroSub: 'Build your on-demand platform for any service — home cleaning, beauty, plumbing and more.',
    heroImage: '/images/generic-1.png',
    overviewFeatures: [
      { title: 'Service Booking & Scheduling', desc: 'Real-time slot booking with calendar management.' },
      { title: 'Service Provider App', desc: 'Dedicated app for professionals to manage bookings.' },
      { title: 'Live Tracking', desc: 'Track the service professional en route to your location.' },
      { title: 'In-App Payments', desc: 'Wallet, UPI, card and COD payment support.' },
      { title: 'Reviews & Ratings', desc: 'Post-service feedback with photo upload.' },
      { title: 'Subscription Packages', desc: 'Weekly and monthly recurring service plans.' },
    ],
    panels: ['Customer App', 'Service Provider App', 'Admin Dashboard', 'Booking Manager'],
    techStack: ['Flutter', 'Node.js', 'MongoDB', 'Google Maps', 'Firebase', 'Razorpay'],
    pricingStarter: '₹1,10,000',
    pricingPro: '₹2,40,000',
    pricingEnterprise: 'Custom',
    relatedSlugs: ['food-delivery', 'taxi-booking', 'custom-mobile-app'],
    faq: [
      { q: 'What types of services can this platform support?', a: 'Any service — home cleaning, beauty, plumbing, tutoring, laundry, fitness and more.' },
      { q: 'Can I have multiple service categories?', a: 'Yes. Unlimited service categories with custom pricing rules per category.' },
      { q: 'Do service providers get their own app?', a: 'Yes. A separate provider app for managing bookings, earnings and availability.' },
      { q: 'Is live tracking included?', a: 'Yes. Customers can track the provider in real-time on a map.' },
      { q: 'Can I offer subscription plans?', a: 'Yes. Weekly, monthly and custom recurring service packages are supported.' },
      { q: 'How are payments handled?', a: 'In-app payment via Razorpay, UPI and cards. Cash is also supported.' },
      { q: 'How long does development take?', a: 'A standard platform takes 8–12 weeks depending on number of service types.' },
      { q: 'Can I manage everything from one admin panel?', a: 'Yes. Full control of users, providers, bookings, payments and analytics.' },
    ],
  },
  'matrimonial-app': {
    slug: 'matrimonial-app',
    metaTitle: 'Matrimonial App Development Company | DevBotics',
    metaDesc: 'Build the next Shaadi.com with DevBotics. AI-powered matrimonial app with smart matchmaking, privacy controls, verified profiles and kundali matching.',
    heroEyebrow: '✦ APP DEVELOPMENT · MATRIMONIAL',
    heroH1: ['Matrimonial App', 'Development'],
    heroAccentWord: 'Company.',
    heroSub: 'Build the next Shaadi.com — AI-powered matchmaking with privacy controls and smart profiles.',
    heroImage: '/images/generic-2.png',
    overviewFeatures: [
      { title: 'Smart Matchmaking', desc: 'AI-based compatibility scoring and profile suggestions.' },
      { title: 'Advanced Profile Filters', desc: 'Caste, profession, location, height, horoscope filters.' },
      { title: 'Privacy Controls', desc: 'Photo blur, profile hide and selective visibility options.' },
      { title: 'Verified Profiles', desc: 'ID and photo verification system with admin approval.' },
      { title: 'In-App Chat', desc: 'Encrypted messaging after mutual interest match.' },
      { title: 'Horoscope Integration', desc: 'Kundali matching and compatibility score display.' },
    ],
    panels: ['User App', 'Admin Panel', 'Verification System', 'Analytics'],
    techStack: ['React Native', 'Python/AI', 'MongoDB', 'Firebase', 'AWS', 'TensorFlow'],
    pricingStarter: '₹1,30,000',
    pricingPro: '₹2,80,000',
    pricingEnterprise: 'Custom',
    relatedSlugs: ['custom-mobile-app', 'on-demand-app', 'ecommerce-app'],
    faq: [
      { q: 'Does the app support AI-based matching?', a: 'Yes. Our AI engine scores compatibility based on preferences, behavior and profile data.' },
      { q: 'Can users hide their photos from certain users?', a: 'Yes. Advanced privacy controls allow selective profile and photo visibility.' },
      { q: 'Is kundali matching supported?', a: 'Yes. Horoscope data and Kundali compatibility scoring are built-in.' },
      { q: 'How are profiles verified?', a: 'Users submit ID documents which admins verify before profiles go live.' },
      { q: 'Can I add premium membership plans?', a: 'Yes. Freemium + paid plans with contact view limits are supported.' },
      { q: 'Is messaging encrypted?', a: 'Yes. All in-app chat is end-to-end encrypted.' },
      { q: 'Can families create and manage profiles?', a: 'Yes. Family accounts with shared profile management are supported.' },
      { q: 'How long does development take?', a: 'A standard matrimonial platform takes 10–16 weeks.' },
    ],
  },
  'custom-mobile-app': {
    slug: 'custom-mobile-app',
    metaTitle: 'Custom Mobile App Development Company | DevBotics',
    metaDesc: 'Your unique idea deserves expert execution. DevBotics builds fully custom iOS and Android apps tailored to your exact business requirements.',
    heroEyebrow: '✦ APP DEVELOPMENT · CUSTOM',
    heroH1: ['Custom Mobile App', 'Development'],
    heroAccentWord: 'Company.',
    heroSub: 'Your unique idea deserves expert execution. We build exactly what you envision — no templates, no compromises.',
    heroImage: '/images/generic-1.png',
    overviewFeatures: [
      { title: 'Idea-to-App Service', desc: 'From concept and wireframe to live app store listing.' },
      { title: 'Any Industry', desc: 'No limitation on domain, complexity or tech stack.' },
      { title: 'Fully Custom UI/UX', desc: 'Designed from scratch to match your exact brand.' },
      { title: 'API & Third-Party Integration', desc: 'Any service, any platform, any external system.' },
      { title: 'Scalable Architecture', desc: 'Built to handle 1 user or 1 million users seamlessly.' },
      { title: 'Source Code Ownership', desc: '100% IP rights and source code transferred to you.' },
    ],
    panels: ['Custom Client App', 'Admin Dashboard', 'API Backend', 'Analytics Panel'],
    techStack: ['React Native', 'Flutter', 'Node.js', 'Python', 'PostgreSQL', 'MongoDB', 'AWS', 'Firebase'],
    pricingStarter: '₹80,000',
    pricingPro: '₹2,00,000',
    pricingEnterprise: 'Custom',
    relatedSlugs: ['food-delivery', 'ecommerce-app', 'healthcare-app'],
    faq: [
      { q: 'What industries do you build custom apps for?', a: 'All industries — fintech, logistics, real estate, fitness, social, gaming and more.' },
      { q: 'Do I need to have a full specification?', a: 'No. We help you define the scope, features and roadmap during free discovery.' },
      { q: 'Which tech stack will you use?', a: 'We recommend based on your needs — React Native or Flutter for cross-platform, native Swift/Kotlin for performance-critical apps.' },
      { q: 'Will I own the code?', a: 'Yes. 100% source code, IP and assets are transferred on final payment.' },
      { q: 'Can you integrate with my existing systems?', a: 'Yes. We integrate with any existing ERP, CRM, database or third-party API.' },
      { q: 'Do you build MVPs?', a: 'Yes. We specialize in lean MVP development to validate ideas quickly and cost-effectively.' },
      { q: 'What is your development process?', a: 'Agile sprints with working builds every 2 weeks, regular demos and open communication.' },
      { q: 'How is the project price determined?', a: 'Based on features, complexity and timeline. We provide a detailed quote after discovery.' },
    ],
  },
};

export const appTypeCards = [
  { slug: 'food-delivery', name: 'Food Delivery App', desc: 'End-to-end food ordering with real-time tracking.', tags: ['React Native', 'Node.js', 'Firebase'], img: '/images/generic-2.png' },
  { slug: 'taxi-booking', name: 'Taxi Booking App', desc: 'Uber-style ride booking with live driver tracking.', tags: ['Flutter', 'Node.js', 'Google Maps'], img: '/images/generic-1.png' },
  { slug: 'ecommerce-app', name: 'E-commerce App', desc: 'Feature-rich shopping app with seamless checkout.', tags: ['React Native', 'Shopify', 'Stripe'], img: '/images/generic-2.png' },
  { slug: 'healthcare-app', name: 'Healthcare App', desc: 'Patient management, telemedicine & health tracking.', tags: ['Flutter', 'Firebase', 'Node.js'], img: '/images/generic-1.png' },
  { slug: 'edtech-app', name: 'EdTech App', desc: 'Live classes, quizzes & progress tracking for students.', tags: ['React Native', 'MongoDB', 'AWS'], img: '/images/generic-2.png' },
  { slug: 'on-demand-app', name: 'On-Demand App', desc: 'Any service, on-demand. Laundry, beauty, home services.', tags: ['Flutter', 'Node.js', 'Stripe'], img: '/images/generic-1.png' },
  { slug: 'matrimonial-app', name: 'Matrimonial App', desc: 'Smart matchmaking with AI-based profile suggestions.', tags: ['React Native', 'Python', 'Firebase'], img: '/images/generic-2.png' },
  { slug: 'custom-mobile-app', name: 'Custom Mobile App', desc: 'Your unique idea. Our expert execution. Let\'s build.', tags: ['React Native', 'Flutter', 'Any Stack'], img: '/images/generic-1.png' },
];

